<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>QObject</name>
    <message>
        <source>氢</source>
        <translation>Hydrogen</translation>
    </message>
    <message>
        <source>氦</source>
        <translation>Helium</translation>
    </message>
    <message>
        <source>锂</source>
        <translation>Lithium</translation>
    </message>
    <message>
        <source>铍</source>
        <translation>Beryllium</translation>
    </message>
    <message>
        <source>硼</source>
        <translation>Boron</translation>
    </message>
    <message>
        <source>碳</source>
        <translation>Carbon</translation>
    </message>
    <message>
        <source>氮</source>
        <translation>Nitrogen</translation>
    </message>
    <message>
        <source>氧</source>
        <translation>Oxygen</translation>
    </message>
    <message>
        <source>氟</source>
        <translation>Fluorine</translation>
    </message>
    <message>
        <source>氖</source>
        <translation>Neon</translation>
    </message>
    <message>
        <source>钠</source>
        <translation>Sodium</translation>
    </message>
    <message>
        <source>镁</source>
        <translation>Magnesium</translation>
    </message>
    <message>
        <source>铝</source>
        <translation>Aluminium</translation>
    </message>
    <message>
        <source>硅</source>
        <translation>Silicon</translation>
    </message>
    <message>
        <source>磷</source>
        <translation>Phosphorus</translation>
    </message>
    <message>
        <source>硫</source>
        <translation>Sulfur</translation>
    </message>
    <message>
        <source>氯</source>
        <translation>Chlorine</translation>
    </message>
    <message>
        <source>氩</source>
        <translation>Argon</translation>
    </message>
    <message>
        <source>钾</source>
        <translation>Potassium</translation>
    </message>
    <message>
        <source>钙</source>
        <translation>Calcium</translation>
    </message>
    <message>
        <source>钪</source>
        <translation>Scandium</translation>
    </message>
    <message>
        <source>钛</source>
        <translation>Titanium</translation>
    </message>
    <message>
        <source>钒</source>
        <translation>Vanadium</translation>
    </message>
    <message>
        <source>铬</source>
        <translation>Chromium</translation>
    </message>
    <message>
        <source>锰</source>
        <translation>Manganese</translation>
    </message>
    <message>
        <source>铁</source>
        <translation>Iron</translation>
    </message>
    <message>
        <source>钴</source>
        <translation>Cobalt</translation>
    </message>
    <message>
        <source>镍</source>
        <translation>Nickel</translation>
    </message>
    <message>
        <source>铜</source>
        <translation>Copper</translation>
    </message>
    <message>
        <source>锌</source>
        <translation>Zinc</translation>
    </message>
    <message>
        <source>镓</source>
        <translation>Gallium</translation>
    </message>
    <message>
        <source>锗</source>
        <translation>Gemanium</translation>
    </message>
    <message>
        <source>砷</source>
        <translation>Arsenic</translation>
    </message>
    <message>
        <source>硒</source>
        <translation>Selenium</translation>
    </message>
    <message>
        <source>溴</source>
        <translation>Bromine</translation>
    </message>
    <message>
        <source>氪</source>
        <translation>Krypton</translation>
    </message>
    <message>
        <source>铷</source>
        <translation>Rubiduim</translation>
    </message>
    <message>
        <source>锶</source>
        <translation>Strontium</translation>
    </message>
    <message>
        <source>钇</source>
        <translation>Yttrium</translation>
    </message>
    <message>
        <source>锆</source>
        <translation>Zirconium</translation>
    </message>
    <message>
        <source>铌</source>
        <translation>Niobium</translation>
    </message>
    <message>
        <source>钼</source>
        <translation>Molybdenum</translation>
    </message>
    <message>
        <source>锝</source>
        <translation>Technetium</translation>
    </message>
    <message>
        <source>钌</source>
        <translation>Ruthenium</translation>
    </message>
    <message>
        <source>铑</source>
        <translation>Rhodium</translation>
    </message>
    <message>
        <source>钯</source>
        <translation>Palladium</translation>
    </message>
    <message>
        <source>银</source>
        <translation>Silver</translation>
    </message>
    <message>
        <source>镉</source>
        <translation>Cadmium</translation>
    </message>
    <message>
        <source>铟</source>
        <translation>Indium</translation>
    </message>
    <message>
        <source>锡</source>
        <translation>Tin</translation>
    </message>
    <message>
        <source>锑</source>
        <translation>Antimony</translation>
    </message>
    <message>
        <source>碲</source>
        <translation>Tellurium</translation>
    </message>
    <message>
        <source>碘</source>
        <translation>Iodine</translation>
    </message>
    <message>
        <source>氙</source>
        <translation>Xenon</translation>
    </message>
    <message>
        <source>铯</source>
        <translation>Caesium</translation>
    </message>
    <message>
        <source>钡</source>
        <translation>Barium</translation>
    </message>
    <message>
        <source>镧</source>
        <translation>Lanthanum</translation>
    </message>
    <message>
        <source>铈</source>
        <translation>Derium</translation>
    </message>
    <message>
        <source>镨</source>
        <translation>Praseodymium</translation>
    </message>
    <message>
        <source>钕</source>
        <translation>Neodymium</translation>
    </message>
    <message>
        <source>钷</source>
        <translation>Promethium</translation>
    </message>
    <message>
        <source>钐</source>
        <translation>Samarium</translation>
    </message>
    <message>
        <source>铕</source>
        <translation>Europium</translation>
    </message>
    <message>
        <source>钆</source>
        <translation>Gadolinium</translation>
    </message>
    <message>
        <source>铽</source>
        <translation>Terbium</translation>
    </message>
    <message>
        <source>镝</source>
        <translation>Dysprosium</translation>
    </message>
    <message>
        <source>钬</source>
        <translation>Holmium</translation>
    </message>
    <message>
        <source>铒</source>
        <translation>Erbium</translation>
    </message>
    <message>
        <source>铥</source>
        <translation>Thulium</translation>
    </message>
    <message>
        <source>镱</source>
        <translation>Ytterbium</translation>
    </message>
    <message>
        <source>镥</source>
        <translation>Luterbium</translation>
    </message>
    <message>
        <source>铪</source>
        <translation>Hafnium</translation>
    </message>
    <message>
        <source>钽</source>
        <translation>Tantalum</translation>
    </message>
    <message>
        <source>钨</source>
        <translation>Tungsten</translation>
    </message>
    <message>
        <source>铼</source>
        <translation>Rhenium</translation>
    </message>
    <message>
        <source>锇</source>
        <translation>Osmium</translation>
    </message>
    <message>
        <source>铱</source>
        <translation>Iridium</translation>
    </message>
    <message>
        <source>铂</source>
        <translation>Platinum</translation>
    </message>
    <message>
        <source>金</source>
        <translation>Gold</translation>
    </message>
    <message>
        <source>汞</source>
        <translation>Mercury</translation>
    </message>
    <message>
        <source>铊</source>
        <translation>Thallium</translation>
    </message>
    <message>
        <source>铅</source>
        <translation>Lead</translation>
    </message>
    <message>
        <source>铋</source>
        <translation>Bismuth</translation>
    </message>
    <message>
        <source>钋</source>
        <translation>Polonium</translation>
    </message>
    <message>
        <source>砹</source>
        <translation>Astatine</translation>
    </message>
    <message>
        <source>氡</source>
        <translation>Radon</translation>
    </message>
    <message>
        <source>钫</source>
        <translation>Francium</translation>
    </message>
    <message>
        <source>镭</source>
        <translation>Radium</translation>
    </message>
    <message>
        <source>锕</source>
        <translation>Actinium</translation>
    </message>
    <message>
        <source>钍</source>
        <translation>Thorium</translation>
    </message>
    <message>
        <source>镤</source>
        <translation>Protactinium</translation>
    </message>
    <message>
        <source>铀</source>
        <translation>Uranium</translation>
    </message>
    <message>
        <source>镎</source>
        <translation>Neptunium</translation>
    </message>
    <message>
        <source>钚</source>
        <translation>Plutonium</translation>
    </message>
    <message>
        <source>镅</source>
        <translation>Americium</translation>
    </message>
    <message>
        <source>锔</source>
        <translation>Curium</translation>
    </message>
    <message>
        <source>锫</source>
        <translation>Berkelium</translation>
    </message>
    <message>
        <source>锎</source>
        <translation>Californium</translation>
    </message>
    <message>
        <source>锿</source>
        <translation>Einsteinium</translation>
    </message>
    <message>
        <source>镄</source>
        <translation>Fermium</translation>
    </message>
    <message>
        <source>钔</source>
        <translation>Mendelevium</translation>
    </message>
    <message>
        <source>锘</source>
        <translation>Nobelium</translation>
    </message>
    <message>
        <source>铹</source>
        <translation>Lawrencium</translation>
    </message>
    <message>
        <source>𬬻</source>
        <translation>Rutherfordium</translation>
    </message>
    <message>
        <source>𬭊</source>
        <translation>Dubnium</translation>
    </message>
    <message>
        <source>𬭳</source>
        <translation>seaborgium</translation>
    </message>
    <message>
        <source>𬭛</source>
        <translation>Bohrium</translation>
    </message>
    <message>
        <source>𬭶</source>
        <translation>Hassium</translation>
    </message>
    <message>
        <source>鿏</source>
        <translation>Meitnerium</translation>
    </message>
    <message>
        <source>𫟼</source>
        <translation>Darmstadtium</translation>
    </message>
    <message>
        <source>𬬭</source>
        <translation>Roentgenium</translation>
    </message>
    <message>
        <source>鿔</source>
        <translation>Copernicium</translation>
    </message>
    <message>
        <source>鿭</source>
        <translation>Nihonium</translation>
    </message>
    <message>
        <source>𫓧</source>
        <translation>Flerovium</translation>
    </message>
    <message>
        <source>镆</source>
        <translation>Moscovium</translation>
    </message>
    <message>
        <source>𫟷</source>
        <translation>Livermorium</translation>
    </message>
    <message>
        <source>鿬</source>
        <translation>Tennessine</translation>
    </message>
    <message>
        <source>鿫</source>
        <translation>Oganesson</translation>
    </message>
</context>
</TS>
